title: Link
description: 怎么去拥有一道彩虹。
keywords: blog,css,html,php
show_downloads: false
show_comment: false

# SEO Tags
defaults:
  - scope:
      path: "" #全站通用
    values:
      image: /avatar/avatar.png

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://atlinker.cn" # change this to the base hostname & protocol for your site

google_analytics:
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#install emoji
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

PJAX: true #启用PJAX，会与评论系统冲突（如不用评论系统建议开启）

paginate: 8
paginate_path: "page:num"

theme_color: "rgba(0,0,0, .5)" #ff5252
background: /theme/bkg2.png

# social
author: "Link"
image: 
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
